# Generated by Django 5.0.4 on 2024-05-17 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('avatar', models.ImageField(default='avatars/default.png', upload_to='avatars/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('adress_of_delivery_line_1', models.CharField(blank=True, max_length=100)),
                ('adress_of_delivery_line_2', models.CharField(blank=True, max_length=100)),
                ('adress_of_city', models.CharField(blank=True, max_length=100)),
                ('adress_of_state', models.CharField(blank=True, max_length=100)),
                ('adress_of_zip', models.CharField(blank=True, max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email_customer', models.EmailField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('add_data', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
