# Generated by Django 5.0.4 on 2024-05-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_customer',
            field=models.EmailField(max_length=100),
        ),
    ]
