# Generated by Django 5.0.4 on 2024-05-19 21:55

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название товара', max_length=100, unique=True, verbose_name='Название товара')),
                ('description', ckeditor.fields.RichTextField(help_text='Введите описание товара', verbose_name='Описание товара')),
                ('image', models.ImageField(default='products/blank.jpg', help_text='Загрузите изображение товара', upload_to='products/', verbose_name='Изображение товара')),
                ('price', models.DecimalField(decimal_places=2, default=999999.99, help_text='Введите цену товара', max_digits=10, verbose_name='Цена товара')),
                ('quantity', models.PositiveSmallIntegerField(default=0, help_text='Введите количество товара', verbose_name='Количество товара')),
                ('product_size', models.CharField(help_text='Введите размер товара', max_length=50, verbose_name='Размер товара')),
                ('product_weight', models.DecimalField(decimal_places=2, help_text='Введите вес товара', max_digits=10, verbose_name='Вес товара')),
                ('delivery_time', models.CharField(help_text='Введите срок доставки', max_length=50, verbose_name='Срок доставки')),
                ('delivery_price', models.DecimalField(decimal_places=2, help_text='Введите стоимость доставки', max_digits=10, verbose_name='Стоимость доставки')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='Дата добавления товара', verbose_name='Дата добавления товара')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, help_text='Введите рейтинг товара', max_digits=3, verbose_name='Рейтинг товара')),
                ('active', models.BooleanField(default=True, help_text='Товар активен или нет', verbose_name='Активный товар')),
                ('brand', models.ForeignKey(help_text='Выберите бренд товара', on_delete=django.db.models.deletion.CASCADE, to='products_app.brand', verbose_name='Бренд товара')),
                ('category', models.ForeignKey(help_text='Выберите категорию товара', on_delete=django.db.models.deletion.CASCADE, to='products_app.category', verbose_name='Категория товара')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение отзыва', null=True, upload_to='reviews/', verbose_name='Изображение отзыва')),
                ('text', models.TextField(help_text='Введите текст отзыва', verbose_name='Текст отзыва')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='Дата добавления отзыва', verbose_name='Дата добавления отзыва')),
                ('active', models.BooleanField(default=True, help_text='Отзыв активен или нет', verbose_name='Активный отзыв')),
                ('product', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, to='products_app.product', verbose_name='Товар')),
                ('user', models.ForeignKey(help_text='Выберите пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
