# Generated by Django 5.0.4 on 2024-05-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(help_text='Выберите размеры товара', to='products_app.productSize', verbose_name='Размеры товара'),
        ),
    ]
