# Generated by Django 5.0.4 on 2024-05-19 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0002_productsize_remove_product_product_size_product_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products_app.productsize')),
            ],
        ),
    ]
