# Generated by Django 5.0.4 on 2024-05-20 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_productsizequantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='category',
            field=models.ForeignKey(default=3, help_text='Выберите категорию размера', on_delete=django.db.models.deletion.CASCADE, to='products_app.category', verbose_name='Категория размера'),
            preserve_default=False,
        ),
    ]
