# Generated by Django 5.0.6 on 2024-05-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0004_productsize_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productsize',
            table='products_app_productsize',
        ),
    ]
