# Generated by Django 5.0.4 on 2024-05-20 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart_app', '0001_initial'),
        ('products_app', '0004_productsize_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products_app.productsize'),
            preserve_default=False,
        ),
    ]
